### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by SpooneyH20** [RedSoloFox/PlaiScript#2]
Build a linux executable?

**Comment by Tenzinn3** [comment]
I'd assume it would work through wine, no?

**Comment by RedSoloFox** [comment]
Download source and run main.py
Dependencies are beautifulsoup4 and pyqt4. Should be all you need besides Python 2.7

**Comment by SpooneyH20** [comment]
You should really put the dependencies in the README then, it may help those on other OSes

**Comment by RedSoloFox** [comment]
Currently checking linux and mac compatibility, then I will update the readme
